include:
  - path: infra/database/docker-compose.yml

  - path: infra/application/docker-compose.yml

  # Only comment this line while you are in development
  - path: infra/monitoring/docker-compose.yml
