spring:
  application:
    name: VietRecruit
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  # kafka:
  #   bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

server:
  port: ${SERVER_PORT:8080}
