spring:
  application:
    name: VietRecruit
    frontend-url: ${FRONTEND_BASE_URL}
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  logging:
    logstash:
      host: 127.0.0.1
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:placeholder}
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/vietrecruit/auth/oauth2/callback/google"
          github:
            client-id: ${GITHUB_CLIENT_ID:placeholder}
            client-secret: ${GITHUB_CLIENT_SECRET:placeholder}
            scope: user:email, read:user
            redirect-uri: "{baseUrl}/vietrecruit/auth/oauth2/callback/github"
        provider:
          github:
            user-name-attribute: login
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_CHAT_MODEL}
      embedding:
        model: ${OPENAI_EMBEDDING_MODEL}
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
resend:
  api-key: ${RESEND_API_KEY}
  domain: vietrecruit.site

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
