apiVersion: 1

datasources:
  - name: Loki
    uid: P8E80F9AEF21F6940
    type: loki
    access: proxy
    url: http://vr-loki:3100
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
