CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_role AS ENUM ('SYSTEM_ADMIN', 'COMPANY_ADMIN', 'HR', 'INTERVIEWER', 'CANDIDATE');
CREATE TYPE job_status AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED');
CREATE TYPE application_status AS ENUM ('NEW', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED');
CREATE TYPE interview_status AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELED');
CREATE TYPE scorecard_result AS ENUM ('PASS', 'FAIL', 'CONSIDERING');
CREATE TYPE offer_status AS ENUM ('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED');
